version: '3.9'

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./php:/var/www/html/

  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: scandiweb
      MYSQL_DATABASE: product_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - dbdata:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata: